language: python

python:
  - "2.7"
  - "3.4"

env:
  matrix:
    - DJANGO=1.7.8 DB=sqlite
    - DJANGO=1.8.12 DB=sqlite
    - DJANGO=1.9.5 DB=sqlite

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install .
  - pip install -q Django==$DJANGO
  - pip install -r test_requirements.txt

# command to run tests
script: python manage.py test --settings=ckeditor_link.tests.settings_test
