name: Release on PYPI
on:
  push:
    branches:  [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.repository == 'bnzk/django-ckeditor-link'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist
        python setup.py bdist_wheel --universal
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER_BNZK }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PW_BNZK }}
      run: twine upload dist/*
